### ISSUE TITLE
Mode block is not displayed in multi monitor setup

### ISSUE THREAD

**Issue by sonnius** [ashfinal/awesome-hammerspoon#20]
The 'Mode block' is not properly displayed in multi monitor setup, when I unplug the external monitors I can see the mode block, would it be an idea to display the mode block on the 'active' screen (similar like in my pull request for cheatsheet https://github.com/ashfinal/awesome-hammerspoon/pull/19)

**Comment by ashfinal** [comment]
Thanks for your advise! I didn't test this config on multi monitors because of hardware absence. But "Reload config" should do the work, making the mode block redisplay on the "active" screen. 

I checked Hammerspoon docs, and found it provides API to watch for external monitors unplug/plug events: [hs.screen.watcher](http://www.hammerspoon.org/docs/hs.screen.watcher.html). But I don't have the condition to run and test. "Reload config" can also be an alternate. 

And alway, PR is welcome. :)
