### ISSUE TITLE
Modal tray is missing

### ISSUE THREAD

**Issue by oroszgy** [ashfinal/awesome-hammerspoon#31]
Just updated my config pulling changes from your repo, and now I cannot see the model status on the bottom right corner. Could you please help me, how can I get it back?

**Comment by ashfinal** [comment]
I guess you may upgate from a quite early version. Since then, lots of things changed. Now we have a small circle on the bottom right corner to indicate in which scene we are. And it only appears when it's very necessary, e.g `Resize` mode, `View` mode, `Timer` mode. 

I made this change because I found the mode block was a little disturbing, and when other mode was activated you would know, no need the extra indicator. For instance, when the cheatsheet webview is showing, you've already known you are in `cheatsheet` mode. I want the scene transform more seamless and less disturbing.

Anyway, there is still a small circle with different color to indicate the current status. When you get familiar with the keybindings, you may even find the circle is disturbing and useless!  I guess you will get used to it and like the change  :)

**Comment by oroszgy** [comment]
I see! Thanks for the answer! :)
