### ISSUE TITLE
CountDown spoon causes switching spaces to focus on Hammerspoon rather than currently visible application

### ISSUE THREAD

**Issue by snowe2010** [ashfinal/awesome-hammerspoon#48]
I disabled all spoons except WinWin (it failed when I tried to disable it). I then added in each spoon one by one until I reproduced the errors I was seeing. 

When switching between spaces every once in a while switching spaces will give focus to Hammerspoon rather than the application it should give focus to. I tracked this issue down to only happen when the CountDown spoon is enabled.

**Comment by ashfinal** [comment]
I couldn't reproduce the errors you saw. Hammerspoon is not supposed to interfere with the current focus.

Can you give me more info about your problem, maybe a screencast?

**Comment by snowe2010** [comment]
![hammerspooncountdown](https://user-images.githubusercontent.com/1534535/38574401-f69256b2-3cb5-11e8-9825-fe3c131ab03f.gif)

So when I switch screens Hammerspoon shows up as active. I click Intellij to bring it into focus and then switch back and forth and then suddenly hammerspoon is active again. This _only_ happens when CountDown is active.

**Comment by ashfinal** [comment]
It seems I've gotten what you were saying. 

I couldn't reproduce the error because I disabled <del>`Show menu icon`</del> `Show dock icon` option from the beginning. 

![hammerspoon_settings](https://user-images.githubusercontent.com/6827900/38599517-775814f2-3d93-11e8-97e3-7ba07e91e840.png)

If this option is on, then while switching spaces Hammerspoon will steal the focus. Maybe it's a flaw of Hammerspoon? 

For now, I suggest you disable this option as well. Hope this will help. :)

**Comment by snowe2010** [comment]
Awesome. It appears to be caused by the `Show dock icon` option and CountDown together which makes a bit more sense. I didn't need to disable the menu icon to get this to stop happening. Thanks!

**Comment by ashfinal** [comment]
@snowe2010 Ew, I meant to say "disable `Show dock icon`"...

Anyway, I'm glad it helps. :)
