### ISSUE TITLE
A alternative window mover approach?

### ISSUE THREAD

**Issue by casouri** [ashfinal/awesome-hammerspoon#52]
With this strategy you can use only four keys`(h/j/k/l)` for eight positions. And another`(c)` for center and another`(f)` for full screen.

![move-window](https://user-images.githubusercontent.com/13118647/38450347-27fe5864-39ea-11e8-9dcc-d00ece165651.gif)

The idea is save the last command, decide the position base on last command and current command.

For example if you press `h` window will go `halfleft`, then you press `k`. Now you have `h+k` which is `cornerNW`. If you press `k` again you now have `k+k`, that will be 'halfup`.

**Comment by ashfinal** [comment]
Sorry for the late reply.

It seems a good idea to decide what to do next base on last command. But in this scenario I think it unnecessary, as we could use one single keystroke  to move the window into `cornerNW`, i.e. `o`. Introducing keystroke sequence only makes things complex and unpredictable. What if users press `h`, then `k`, meanwhile they actually expect the window to go `halfup`, rather than to go `cornerNW`? How do we decide when we respect the last command?

As far as I see, "flatten" keybindings benefit users. Still, thanks for your advice. 😃

**Comment by casouri** [comment]
👍

**Comment by casouri** [comment]
Oh and if you press h k k, the window will go halfup.

**Comment by ashfinal** [comment]
@casouri A quick hint: while in `Resize window` mode, press `Tab` to show all available keybindings.

**Comment by casouri** [comment]
OK 👌
