### ISSUE TITLE
Can I only use left alt with hammerspoon?

### ISSUE THREAD

**Issue by scottming** [ashfinal/awesome-hammerspoon#54]
I use Emacs write things, sometimes will press `alt` key as a meta key. So I want to know can I only use left `alt` key with hammerspoon, then I can use right `alt` key with Emacs.

**Comment by ashfinal** [comment]
Unfortunately, this couldn't be done with Hammerspoon. Because like most softwares, Hammerspooon can't distinguish the left `alt` key with right `alt` key right now.

One solution is in Emacs you can use `cmd` as meta key, since Emacs is such a flexible software.

Another is through [Karabiner-Elements](https://github.com/tekezo/Karabiner-Elements). You can refer to the official manual.

Hope this will be helpful. :)
