### ISSUE TITLE
winhints_keys overlays options so you can't see them

### ISSUE THREAD

**Issue by nikivdev** [ashfinal/awesome-hammerspoon#9]
For example I trigger it and have two active windows but I can't see what the other window is : 

![2016-12-31 at 16 25](https://cloud.githubusercontent.com/assets/6391776/21578134/bda1a12c-cf75-11e6-8c67-4abb30b04ab1.png)

Would it be possible to smartly rearrange them so you can always see the names of the windows, and also preserve lettering for each window, so you can remember what each window represents to quickly go back to it. I guess it does preserve the lettering, but haven't checked it when many active windows are open.

Thank you for any help.

**Comment by nikivdev** [comment]
Just to note, this seems to be a bug, since often it actually does rearrange them nicely. :)

**Comment by ashfinal** [comment]
Thanks for feedback! 

Window hints will show their titles if there are less than 4 windows on screen by default.
I’ve never found this flaw because I barely use this functionality if there are not “enough” windows. : )

Given the situation, showing windows’ title may not be a good idea, the lettering is good enough. More clean and free-distraction.

You can put the line below into `~/.hammerspoon/private/awesomeconfig.lua` to make it work (if the file don’t exists, just create it).

`hs.hints.showTitleThresh = 0`

I will turn this option on by default on next commit (if no objection).

**Comment by nikivdev** [comment]
Oh no, I actually like to have the titles shown. Because if they are hidden, how do I know which one of Safari windows is which : 

![2017-01-01 at 13 54](https://cloud.githubusercontent.com/assets/6391776/21581246/d2c8a190-d029-11e6-88e7-bac02f3fbb8e.png)

The only way to know is to go to press C and B, and see which one is which and then remember which I don't think is a good choice.

**Comment by ashfinal** [comment]
You can tell the difference by the window's rough position, from my experience.

`hs.hints.showTitleThresh = 0`

And feel free to change the number to whatever you need.
